version: '3'

services:
  app:
    build: ./app.Dockerfile
    ports: 
      - 4200:4200
      - 1668:1668
      - 1864:1864
    volumes: 
      - './:/app'
      - node_modules_volume:/app/node_modules
    tty: true
volumes:
  node_modules_volume: